CREATE TABLE PACIENTE ( 
	PACIENTEID NUMBER PRIMARY KEY, 
	NOMEPACIENTE VARCHAR2(80) NOT NULL, 
	CPF VARCHAR2(14) NOT NULL,
	DATANASCIMENTO DATE NOT NULL,
	GENERO VARCHAR2(50) NOT NULL,
	ENDERECO VARCHAR2(200) NOT NULL,
	CONTATO VARCHAR2(200) NOT NULL
); 
 
CREATE SEQUENCE PACIENTE_ID_SEQ;  
 
CREATE OR REPLACE TRIGGER TR_SEQ_PACIENTE BEFORE INSERT ON PACIENTE FOR EACH ROW  
BEGIN 
	SELECT PACIENTE_ID_SEQ.NEXTVAL INTO :new.PACIENTEID FROM dual; 
END; 
 
--DROP TRIGGER TR_SEQ_PACIENTE; 
--DROP SEQUENCE PACIENTE_ID_SEQ; 
--DROP TABLE PACIENTE;   



CREATE TABLE MEDICO ( 
	MEDICOID NUMBER PRIMARY KEY, 
	NOMEMEDICO VARCHAR2(80) NOT NULL, 
	CRM VARCHAR2(14) NOT NULL,
	ESPECIALIDADE VARCHAR2(100) NOT NULL,
	CONTATO VARCHAR2(200) NOT NULL
); 
 
CREATE SEQUENCE MEDICO_ID_SEQ;  
 
CREATE OR REPLACE TRIGGER TR_SEQ_MEDICO BEFORE INSERT ON MEDICO FOR EACH ROW  
BEGIN 
	SELECT MEDICO_ID_SEQ.NEXTVAL INTO :new.MEDICOID FROM dual; 
END; 
 
--DROP TRIGGER TR_SEQ_MEDICO; 
--DROP SEQUENCE MEDICO_ID_SEQ; 
--DROP TABLE MEDICO;   



CREATE TABLE PRONTUARIO (
    PRONTUARIOID NUMBER PRIMARY KEY,
    PACIENTEID NUMBER,
    HISTORICOPACIENTE VARCHAR2(4000),
    MEDICAMENTO VARCHAR2(1000),
    TRIAGEM VARCHAR2(1000),
    HISTORICOFAMILIAR VARCHAR2(2000),
    EXAMES VARCHAR2(4000),
    DATAPRONTUARIO DATE,
    MEDICOID NUMBER,
    FOREIGN KEY (PACIENTEID) REFERENCES PACIENTE(PACIENTEID),
    FOREIGN KEY (MEDICOID) REFERENCES MEDICO(MEDICOID)
);

CREATE SEQUENCE PRONTUARIO_ID_SEQ;

CREATE OR REPLACE TRIGGER TR_SEQ_PRONTUARIO BEFORE INSERT ON PRONTUARIO FOR EACH ROW  
BEGIN 
	SELECT PRONTUARIO_ID_SEQ.NEXTVAL INTO :new.PRONTUARIOID FROM dual; 
END;

--DROP TRIGGER TR_SEQ_PRONTUARIO; 
--DROP SEQUENCE PRONTUARIO_ID_SEQ; 
--DROP TABLE PRONTUARIO; 
